pipeline {
    agent any
    parameters {
        stashedFile(name: 'script.jmx', description: 'Arquivo JMeter (.jmx)')
        stashedFile(name: 'datapool.csv', description: 'Arquivo Datapool')
    }
    stages {
        stage('Executar Teste e Gera Relatorio') {
            steps {
                script {
                    unstash 'script.jmx'
                    unstash 'datapool.csv'
                    try {
                
                       

                        sh """
                        jmeter -n -t script.jmx \
                        -l report${env.BUILD_NUMBER}.jtl \
                        -e -o report${env.BUILD_NUMBER}
                        """

                        echo "Teste concluído com sucesso"
                    } catch (Exception e) {
                        echo "Teste falhou: ${e.getMessage()}"
                        error("Falha na execução do teste")
                    }
                }
            }
        }
    }
}
